import {App, Notice, TFile, normalizePath, requireApiVersion} from "obsidian";
import type {WhisperCalSettings} from "../settings";
import {ensureFolder} from "../utils/vault";

/**
 * The generated Obsidian Bases file over the meeting-notes folder.
 *
 * The calendar sidebar is one day at a time; this is the cross-day view (what
 * is stuck in the pipeline, who the user met with, which meetings someone
 * declined). It is written once on first use and never rewritten, so the user
 * owns it from then on — edit, add views, move it.
 */
const MEETINGS_BASE_FILENAME = "WhisperCal Meetings.base";

/**
 * View names are a contract: the README tells users to embed
 * `![[WhisperCal Meetings.base#Linked to this note]]` in their People-note
 * template, so renaming a view here breaks existing embeds.
 */
const MEETINGS_BASE_LINKED_VIEW = "Linked to this note";

/** Kanban is a core Bases layout from Obsidian 1.14; older apps show an error for an unknown view type. */
const KANBAN_MIN_APP_VERSION = "1.14.0";

/** YAML single-quoted scalar: the only escape is doubling the quote. */
function yamlSingle(s: string): string {
	return `'${s.replace(/'/g, "''")}'`;
}

/** Bases string literal (double-quoted, JSON escaping is a superset of what Bases needs). */
function basesString(s: string): string {
	return JSON.stringify(s);
}

function buildMeetingsBase(noteFolder: string, withKanban: boolean): string {
	const inFolder = yamlSingle(`file.inFolder(${basesString(noteFolder)})`);
	const lines: string[] = [
		"# Generated by WhisperCal (\"Open meetings base\"). WhisperCal never rewrites this",
		"# file, so edit the views freely. Delete it and run the command again to regenerate.",
		"filters:",
		"  and:",
		`    - ${inFolder}`,
		"    - file.hasProperty(\"meeting_date\")",
		"    - '!file.hasProperty(\"merged_into\")'",
		"formulas:",
		"  when: date(meeting_date)",
		"properties:",
		"  file.name:",
		"    displayName: Meeting",
		"  meeting_date:",
		"    displayName: Date",
		"  meeting_start:",
		"    displayName: Start",
		"  meeting_end:",
		"    displayName: End",
		"  meeting_organizer:",
		"    displayName: Organizer",
		"  meeting_invitees:",
		"    displayName: Invitees",
		"  meeting_declined:",
		"    displayName: Declined",
		"  pipeline_state:",
		"    displayName: Pipeline",
		"  research_state:",
		"    displayName: Research",
		"views:",
		"  - type: table",
		"    name: Recent",
		"    filters:",
		"      and:",
		"        - 'formula.when >= today() - \"14d\"'",
		"        - 'formula.when < today() + \"1d\"'",
		"    order:",
		"      - file.name",
		"      - note.meeting_date",
		"      - note.meeting_start",
		"      - note.meeting_organizer",
		"      - note.pipeline_state",
		"      - note.research_state",
		"    sort:",
		"      - property: note.meeting_date",
		"        direction: DESC",
		"      - property: note.meeting_start",
		"        direction: DESC",
		"  - type: table",
		"    name: Upcoming",
		"    filters:",
		"      and:",
		"        - formula.when >= today()",
		"    order:",
		"      - file.name",
		"      - note.meeting_date",
		"      - note.meeting_start",
		"      - note.meeting_organizer",
		"      - note.research_state",
		"      - note.meeting_declined",
		"    sort:",
		"      - property: note.meeting_date",
		"        direction: ASC",
		"      - property: note.meeting_start",
		"        direction: ASC",
		"  - type: table",
		"    name: Needs attention",
		"    filters:",
		"      and:",
		"        - formula.when < today()",
		"        - 'pipeline_state != \"summarized\"'",
		"    order:",
		"      - file.name",
		"      - note.meeting_date",
		"      - note.pipeline_state",
		"      - note.meeting_organizer",
		"    sort:",
		"      - property: note.meeting_date",
		"        direction: DESC",
	];
	if (withKanban) {
		lines.push(
			"  - type: kanban",
			"    name: Pipeline",
			"    groupBy:",
			"      property: note.pipeline_state",
			"      direction: ASC",
			"    groupOrder:",
			"      - note",
			"      - titled",
			"      - transcript",
			"      - tagged",
			"      - summarized",
			"    order:",
			"      - note.meeting_date",
			"      - note.meeting_organizer",
			"    sort:",
			"      - property: note.meeting_date",
			"        direction: DESC",
		);
	}
	lines.push(
		"  - type: table",
		"    name: By organizer",
		"    groupBy:",
		"      property: note.meeting_organizer",
		"      direction: ASC",
		"    order:",
		"      - file.name",
		"      - note.meeting_date",
		"      - note.pipeline_state",
		"    sort:",
		"      - property: note.meeting_date",
		"        direction: DESC",
		"  - type: table",
		`    name: ${MEETINGS_BASE_LINKED_VIEW}`,
		"    # `this` is the embedding note, or the active note when the base is in a sidebar.",
		"    filters:",
		"      and:",
		"        - file.hasLink(this.file)",
		"    order:",
		"      - file.name",
		"      - note.meeting_date",
		"      - note.meeting_organizer",
		"      - note.pipeline_state",
		"    sort:",
		"      - property: note.meeting_date",
		"        direction: DESC",
		"  - type: table",
		"    name: All",
		"    order:",
		"      - file.name",
		"      - note.meeting_date",
		"      - note.meeting_start",
		"      - note.meeting_organizer",
		"      - note.pipeline_state",
		"      - note.research_state",
		"    sort:",
		"      - property: note.meeting_date",
		"        direction: DESC",
		"      - property: note.meeting_start",
		"        direction: DESC",
	);
	return lines.join("\n") + "\n";
}

/**
 * Open the meetings base, generating it in the notes folder on first use.
 * An existing file is opened as-is — it belongs to the user once written.
 */
export async function openMeetingsBase(app: App, settings: WhisperCalSettings): Promise<void> {
	const folder = normalizePath(settings.noteFolderPath || "Meetings");
	const path = normalizePath(`${folder}/${MEETINGS_BASE_FILENAME}`);
	let file = app.vault.getAbstractFileByPath(path);
	if (!file) {
		await ensureFolder(app, folder);
		file = await app.vault.create(path, buildMeetingsBase(folder, requireApiVersion(KANBAN_MIN_APP_VERSION)));
		new Notice(`Created ${path}`);
	}
	if (!(file instanceof TFile)) {
		new Notice(`${path} exists but is not a file`);
		return;
	}
	await app.workspace.getLeaf(false).openFile(file);
}
