import {homedir} from "os";
import {join} from "path";
import process from "process";

export const VIEW_TYPE_CALENDAR = "whisper-cal-calendar-view";
export const COMMAND_OPEN_CALENDAR = "open-calendar-view";
export const COMMAND_LINK_RECORDING = "link-macwhisper-recording";
export const COMMAND_TAG_SPEAKERS = "tag-speakers";
export const COMMAND_SUMMARIZE = "summarize-transcript";
export const COMMAND_RESEARCH = "research-meeting";
export const COMMAND_WORD_REPLACE = "run-word-replacements";
export const COMMAND_OPEN_SERIES_NOTE = "open-meeting-series-note";

/**
 * Tome writes its dynamic API port to a file in its per-user data dir. The
 * location is platform-specific: `~/Library/Application Support/Tome` on macOS,
 * `%APPDATA%\Tome` (Roaming) on Windows. This is a contract with the Tome
 * Windows port — the manual Base URL setting is the escape hatch if it differs.
 */
function tomeDataDir(): string {
	if (process.platform === "win32") {
		return join(process.env.APPDATA ?? join(homedir(), "AppData", "Roaming"), "Tome");
	}
	return join(homedir(), "Library", "Application Support", "Tome");
}
export const RECORDING_API_PORT_FILE = join(tomeDataDir(), "api-port");

const MW_BASE = join(homedir(), "Library", "Application Support", "MacWhisper");
export const MACWHISPER_DB_PATH = join(MW_BASE, "Database", "main.sqlite");
export const MACWHISPER_MEDIA_PATH = join(MW_BASE, "Database", "ExternalMedia");

/**
 * Frontmatter keys read/written across the pipeline. Centralized so renames are mechanical
 * and typos are caught at compile time.
 */
export const FM = {
	PIPELINE_STATE: "pipeline_state",
	MEETING_INVITEES: "meeting_invitees",
	CALENDAR_ATTENDEES: "calendar_attendees",
	INVITEES: "invitees",
	MACWHISPER_SESSION_ID: "macwhisper_session_id",
	MACWHISPER_SESSION_IDS: "macwhisper_session_ids",
	// Correlation id linking a meeting note, its Tome recording session, and the
	// resulting transcript (SESSION_GUID_DESIGN.md). Generated by WhisperCal at
	// record-start, echoed by Tome, and stamped by Tome into the transcript.
	SESSION_GUID: "session_guid",
	MERGED_FROM: "merged_from",
	// Backlink written onto each original note when it is merged. Presence of
	// this key hides the note's card in the calendar (both its local card and
	// the underlying Graph event card); the merged note is the source of truth.
	MERGED_INTO: "merged_into",
	TRANSCRIPT: "transcript",
	MEETING_NOTE: "meeting_note",
	CALENDAR_EVENT_ID: "calendar_event_id",
	MEETING_SERIES_ID: "meeting_series_id",
	CONFIRMED_SPEAKERS: "confirmed_speakers",
	VOICEPRINTS: "voiceprints",
	// Research is orthogonal to the linear pipeline (it runs as pre-meeting prep
	// or post-summary), so its completion lives in its own field rather than in
	// pipeline_state, which would otherwise be clobbered by later transcript/
	// summary writes. Set to "research-done" by the plugin on a successful run.
	RESEARCH_STATE: "research_state",
} as const;

/** Valid values written to `pipeline_state` across the pipeline. */
export type PipelineState = "note" | "titled" | "transcript" | "tagged" | "summarized";
